# PRISM-4D pub baseline validation overlay — Kv1.2
# Generated by prism_pub_baseline_validator.py

load /mnt/storage/prism-outputs/blind_validation/B03_Kv1.2/prep/3LUT_clean.pdb, query_Kv1.2
hide everything, query_Kv1.2
show cartoon,    query_Kv1.2
color grey80,    query_Kv1.2

# Site 13 [CRYPTIC] q=0.373 verdict=STRONG
# Site 4015 [DYNAMIC] q=0.356 verdict=STRONG
# Site 4010 [CRYPTIC] q=0.288 verdict=STRONG
# Site 3015 [RESPONSIVE] q=0.272 verdict=STRONG
# Site 11 [INERT] q=0.438 verdict=NEAR
# Site 7 [CRYPTIC] q=0.425 verdict=NEAR
# Site 4517 [RESPONSIVE] q=0.418 verdict=NEAR
# Site 5 [INERT] q=0.413 verdict=NEAR
# Site 4011 [RESPONSIVE] q=0.409 verdict=NEAR
# Site 12 [RESPONSIVE] q=0.299 verdict=NEAR
# Site 10 [DYNAMIC] q=0.284 verdict=NEAR
# Site 1 [INERT] q=0.234 verdict=NEAR
# Site 518 [INERT] q=0.182 verdict=NEAR
# Site 4519 [DYNAMIC] q=0.401 verdict=MISS
# Site 3525 [RESPONSIVE] q=0.399 verdict=MISS
# Site 4005 [RESPONSIVE] q=0.392 verdict=MISS
# Site 520 [DYNAMIC] q=0.351 verdict=MISS
# Site 4016 [INERT] q=0.294 verdict=MISS
# Site 17 [INERT] q=0.293 verdict=MISS
# Site 4006 [CRYPTIC] q=0.281 verdict=MISS
zoom query_Kv1.2

# Verdict colour legend:
#   STRONG          -> red
#   GOOD_BOTH       -> orange
#   GOOD_DIST       -> yellow
#   GOOD_JACCARD    -> green
#   NEAR            -> cyan
#   WEAK            -> blue
#   MISS            -> grey60
