# PRISM4D Binding Site Visualization
# Generated by prism-nhs
# Industry-standard pocket visualization

# Setup
bg_color white
set cartoon_fancy_helices, 1
set cartoon_side_chain_helper, 1
set surface_quality, 1

# Load your structure (adjust path as needed)
# load 16_GBA_apo.topology.pdb, protein
# show cartoon, protein
# color gray80, protein

# ========== Site 1 (ActiveSite) ==========
select pocket_1_lining, (chain B and resi 812) or (chain A and resi 315) or (chain B and resi 842) or (chain B and resi 843) or (chain A and resi 345) or (chain B and resi 841) or (chain A and resi 344) or (chain B and resi 809) or (chain A and resi 346) or (chain B and resi 811) or (chain B and resi 844) or (chain A and resi 312) or (chain A and resi 348) or (chain B and resi 813) or (chain A and resi 314) or (chain B and resi 845) or (chain A and resi 311) or (chain B and resi 808) or (chain B and resi 840) or (chain A and resi 316)
show sticks, pocket_1_lining
set stick_radius, 0.15, pocket_1_lining
select pocket_1_catalytic, (chain A and resi 345) or (chain A and resi 344) or (chain A and resi 346) or (chain A and resi 348)
color magenta, pocket_1_catalytic
select pocket_1_aromatic, (chain A and resi 315) or (chain A and resi 312) or (chain A and resi 314) or (chain A and resi 311) or (chain A and resi 316)
color forest, pocket_1_aromatic
select pocket_1_hydrophobic, (chain B and resi 812) or (chain B and resi 809) or (chain B and resi 811) or (chain B and resi 813) or (chain B and resi 808)
color tv_yellow, pocket_1_hydrophobic
create pocket_1_surface, pocket_1_lining
show surface, pocket_1_surface
set surface_color, slate, pocket_1_surface
set transparency, 0.7, pocket_1_surface
pseudoatom pocket_1_center, pos=[-0.976, -6.840, 40.204]
show spheres, pocket_1_center
set sphere_scale, 0.5, pocket_1_center
color gray50, pocket_1_center
group pocket_1, pocket_1_lining pocket_1_surface pocket_1_center pocket_1_catalytic pocket_1_aromatic pocket_1_hydrophobic

# ========== Site 2 (ActiveSite) [DRUGGABLE] ==========
select pocket_2_lining, (chain D and resi 1702) or (chain D and resi 1637) or (chain D and resi 1706) or (chain D and resi 1703) or (chain D and resi 1705) or (chain D and resi 1701) or (chain D and resi 1634) or (chain D and resi 1625) or (chain D and resi 1704) or (chain D and resi 1613) or (chain D and resi 1699) or (chain D and resi 1707) or (chain D and resi 1626) or (chain D and resi 1672) or (chain D and resi 1700) or (chain D and resi 1698) or (chain D and resi 1708) or (chain D and resi 1668) or (chain D and resi 1624) or (chain D and resi 1639) or (chain D and resi 1671) or (chain D and resi 1709) or (chain D and resi 1614) or (chain D and resi 1638) or (chain D and resi 1675)
show sticks, pocket_2_lining
set stick_radius, 0.15, pocket_2_lining
select pocket_2_catalytic, (chain D and resi 1672) or (chain D and resi 1668) or (chain D and resi 1671) or (chain D and resi 1675)
color magenta, pocket_2_catalytic
select pocket_2_aromatic, (chain D and resi 1637) or (chain D and resi 1634) or (chain D and resi 1625) or (chain D and resi 1613) or (chain D and resi 1626) or (chain D and resi 1624) or (chain D and resi 1639) or (chain D and resi 1614) or (chain D and resi 1638)
color forest, pocket_2_aromatic
select pocket_2_hydrophobic, (chain D and resi 1702) or (chain D and resi 1706) or (chain D and resi 1703) or (chain D and resi 1705) or (chain D and resi 1701) or (chain D and resi 1704) or (chain D and resi 1699) or (chain D and resi 1707) or (chain D and resi 1700) or (chain D and resi 1698) or (chain D and resi 1708) or (chain D and resi 1709)
color tv_yellow, pocket_2_hydrophobic
create pocket_2_surface, pocket_2_lining
show surface, pocket_2_surface
set surface_color, slate, pocket_2_surface
set transparency, 0.7, pocket_2_surface
pseudoatom pocket_2_center, pos=[-29.584, -37.527, 49.261]
show spheres, pocket_2_center
set sphere_scale, 0.5, pocket_2_center
color red, pocket_2_center
group pocket_2, pocket_2_lining pocket_2_surface pocket_2_center pocket_2_catalytic pocket_2_aromatic pocket_2_hydrophobic

# ========== Site 3 (ActiveSite) ==========
select pocket_3_lining, (chain A and resi 211) or (chain A and resi 146) or (chain A and resi 212) or (chain A and resi 215) or (chain A and resi 214) or (chain A and resi 210) or (chain A and resi 143) or (chain A and resi 134) or (chain A and resi 122) or (chain A and resi 213) or (chain A and resi 208) or (chain A and resi 216) or (chain A and resi 209) or (chain A and resi 207) or (chain A and resi 135) or (chain A and resi 181) or (chain A and resi 177) or (chain A and resi 217) or (chain A and resi 148) or (chain A and resi 218) or (chain A and resi 133) or (chain A and resi 180) or (chain A and resi 123) or (chain A and resi 263) or (chain A and resi 184) or (chain A and resi 267)
show sticks, pocket_3_lining
set stick_radius, 0.15, pocket_3_lining
select pocket_3_catalytic, (chain A and resi 122) or (chain A and resi 181) or (chain A and resi 177) or (chain A and resi 180) or (chain A and resi 123) or (chain A and resi 263) or (chain A and resi 184)
color magenta, pocket_3_catalytic
select pocket_3_aromatic, (chain A and resi 143) or (chain A and resi 134) or (chain A and resi 135) or (chain A and resi 133)
color forest, pocket_3_aromatic
select pocket_3_hydrophobic, (chain A and resi 211) or (chain A and resi 212) or (chain A and resi 215) or (chain A and resi 214) or (chain A and resi 210) or (chain A and resi 213) or (chain A and resi 208) or (chain A and resi 216) or (chain A and resi 209) or (chain A and resi 207) or (chain A and resi 217) or (chain A and resi 218)
color tv_yellow, pocket_3_hydrophobic
create pocket_3_surface, pocket_3_lining
show surface, pocket_3_surface
set surface_color, slate, pocket_3_surface
set transparency, 0.7, pocket_3_surface
pseudoatom pocket_3_center, pos=[-30.771, -3.503, 31.459]
show spheres, pocket_3_center
set sphere_scale, 0.5, pocket_3_center
color gray50, pocket_3_center
group pocket_3, pocket_3_lining pocket_3_surface pocket_3_center pocket_3_catalytic pocket_3_aromatic pocket_3_hydrophobic

# ========== Site 4 (ActiveSite) ==========
select pocket_4_lining, (chain C and resi 1205) or (chain C and resi 1140) or (chain C and resi 1206) or (chain C and resi 1208) or (chain C and resi 1209) or (chain C and resi 1204) or (chain C and resi 1137) or (chain C and resi 1128) or (chain C and resi 1116) or (chain C and resi 1207) or (chain C and resi 1202) or (chain C and resi 1210) or (chain C and resi 1203) or (chain C and resi 1201) or (chain C and resi 1129) or (chain C and resi 1175) or (chain C and resi 1171) or (chain C and resi 1211) or (chain C and resi 1142) or (chain C and resi 1212) or (chain C and resi 1127) or (chain C and resi 1174) or (chain C and resi 1178) or (chain C and resi 1117) or (chain C and resi 1257) or (chain C and resi 1141) or (chain C and resi 1261)
show sticks, pocket_4_lining
set stick_radius, 0.15, pocket_4_lining
select pocket_4_catalytic, (chain C and resi 1205) or (chain C and resi 1206) or (chain C and resi 1208) or (chain C and resi 1209) or (chain C and resi 1204) or (chain C and resi 1207) or (chain C and resi 1202) or (chain C and resi 1210) or (chain C and resi 1203) or (chain C and resi 1201) or (chain C and resi 1171)
color magenta, pocket_4_catalytic
select pocket_4_aromatic, (chain C and resi 1128) or (chain C and resi 1116) or (chain C and resi 1129) or (chain C and resi 1127) or (chain C and resi 1117)
color forest, pocket_4_aromatic
select pocket_4_hydrophobic, (chain C and resi 1175) or (chain C and resi 1174) or (chain C and resi 1178) or (chain C and resi 1257) or (chain C and resi 1261)
color tv_yellow, pocket_4_hydrophobic
create pocket_4_surface, pocket_4_lining
show surface, pocket_4_surface
set surface_color, slate, pocket_4_surface
set transparency, 0.7, pocket_4_surface
pseudoatom pocket_4_center, pos=[30.504, -43.915, 31.475]
show spheres, pocket_4_center
set sphere_scale, 0.5, pocket_4_center
color gray50, pocket_4_center
group pocket_4, pocket_4_lining pocket_4_surface pocket_4_center pocket_4_catalytic pocket_4_aromatic pocket_4_hydrophobic

# ========== Site 5 (ActiveSite) ==========
select pocket_5_lining, (chain D and resi 1806) or (chain C and resi 1309) or (chain D and resi 1836) or (chain D and resi 1837) or (chain D and resi 1835) or (chain C and resi 1339) or (chain C and resi 1338) or (chain D and resi 1803) or (chain D and resi 1838) or (chain D and resi 1805) or (chain C and resi 1340) or (chain C and resi 1306) or (chain D and resi 1839) or (chain C and resi 1308) or (chain D and resi 1834) or (chain D and resi 1807)
show sticks, pocket_5_lining
set stick_radius, 0.15, pocket_5_lining
select pocket_5_hydrophobic, (chain C and resi 1309) or (chain D and resi 1836) or (chain D and resi 1837) or (chain D and resi 1835) or (chain C and resi 1339) or (chain C and resi 1338) or (chain D and resi 1838) or (chain C and resi 1340) or (chain C and resi 1306) or (chain D and resi 1839) or (chain C and resi 1308) or (chain D and resi 1834)
color tv_yellow, pocket_5_hydrophobic
create pocket_5_surface, pocket_5_lining
show surface, pocket_5_surface
set surface_color, slate, pocket_5_surface
set transparency, 0.7, pocket_5_surface
pseudoatom pocket_5_center, pos=[0.797, -40.151, 39.891]
show spheres, pocket_5_center
set sphere_scale, 0.5, pocket_5_center
color gray50, pocket_5_center
group pocket_5, pocket_5_lining pocket_5_surface pocket_5_center pocket_5_hydrophobic

# ========== Site 6 (ActiveSite) ==========
select pocket_6_lining, (chain B and resi 708) or (chain B and resi 643) or (chain B and resi 709) or (chain B and resi 712) or (chain B and resi 711) or (chain B and resi 707) or (chain B and resi 640) or (chain B and resi 619) or (chain B and resi 710) or (chain B and resi 631) or (chain B and resi 705) or (chain B and resi 713) or (chain B and resi 706) or (chain B and resi 704) or (chain B and resi 678) or (chain B and resi 632) or (chain B and resi 674) or (chain B and resi 714) or (chain B and resi 715) or (chain B and resi 645) or (chain B and resi 677) or (chain B and resi 630) or (chain B and resi 764) or (chain B and resi 760) or (chain B and resi 620) or (chain B and resi 681)
show sticks, pocket_6_lining
set stick_radius, 0.15, pocket_6_lining
select pocket_6_hydrophobic, (chain B and resi 764) or (chain B and resi 760)
color tv_yellow, pocket_6_hydrophobic
create pocket_6_surface, pocket_6_lining
show surface, pocket_6_surface
set surface_color, slate, pocket_6_surface
set transparency, 0.7, pocket_6_surface
pseudoatom pocket_6_center, pos=[28.873, -9.239, 48.988]
show spheres, pocket_6_center
set sphere_scale, 0.5, pocket_6_center
color gray50, pocket_6_center
group pocket_6, pocket_6_lining pocket_6_surface pocket_6_center pocket_6_hydrophobic

group all_pockets, pocket_1 pocket_2 pocket_3 pocket_4 pocket_5 pocket_6

# ========== Color Legend ==========
# Magenta = Catalytic residues (GLU, ASP, HIS, SER, CYS, LYS)
# Green = Aromatic residues (PHE, TYR, TRP) - pi-stacking
# Yellow = Hydrophobic residues (ALA, VAL, LEU, ILE, MET, PRO)
# Slate surface = Pocket cavity
# Red sphere = Druggable site centroid
# Gray sphere = Non-druggable site centroid

# ========== Usage Tips ==========
# To view specific pocket: disable all_pockets, enable pocket_N
# To zoom on pocket: zoom pocket_N_lining
# To show H-bonds: select donors, pocket_N_lining; distance hbonds, donors, acceptors, 3.5
# To label residues: label pocket_N_lining and name CA, "%s%s" % (resn, resi)
