# PRISM-4D pub baseline validation overlay — ADRB2
# Generated by prism_pub_baseline_validator.py

load /mnt/storage/prism-outputs/blind_validation/B10_ADRB2/prep/2RH1_clean.pdb, query_ADRB2
hide everything, query_ADRB2
show cartoon,    query_ADRB2
color grey80,    query_ADRB2

# Site 3537 [INERT] q=0.436 verdict=STRONG
# Site 516 [RESPONSIVE] q=0.430 verdict=STRONG
# Site 1519 [INERT] q=0.393 verdict=STRONG
# Site 1531 [INERT] q=0.391 verdict=STRONG
# Site 1520 [RESPONSIVE] q=0.387 verdict=STRONG
# Site 1532 [INERT] q=0.383 verdict=STRONG
# Site 1521 [INERT] q=0.370 verdict=STRONG
# Site 1533 [INERT] q=0.364 verdict=STRONG
# Site 1529 [INERT] q=0.349 verdict=STRONG
# Site 5528 [INERT] q=0.326 verdict=STRONG
# Site 4528 [INERT] q=0.305 verdict=STRONG
# Site 1528 [INERT] q=0.289 verdict=STRONG
# Site 16 [DYNAMIC] q=0.235 verdict=STRONG
# Site 1525 [DYNAMIC] q=0.396 verdict=NEAR
# Site 3544 [DYNAMIC] q=0.395 verdict=NEAR
# Site 3545 [DYNAMIC] q=0.391 verdict=NEAR
# Site 3546 [DYNAMIC] q=0.391 verdict=NEAR
# Site 4526 [DYNAMIC] q=0.379 verdict=NEAR
# Site 3518 [DYNAMIC] q=0.341 verdict=NEAR
# Site 518 [INERT] q=0.287 verdict=MISS
zoom query_ADRB2

# Verdict colour legend:
#   STRONG          -> red
#   GOOD_BOTH       -> orange
#   GOOD_DIST       -> yellow
#   GOOD_JACCARD    -> green
#   NEAR            -> cyan
#   WEAK            -> blue
#   MISS            -> grey60
