# PRISM-4D pub baseline validation overlay — CRBN
# Generated by prism_pub_baseline_validator.py

load /mnt/storage/prism-outputs/blind_validation/B08_CRBN/prep/4TZ4_chainC_clean.pdb, query_CRBN
hide everything, query_CRBN
show cartoon,    query_CRBN
color grey80,    query_CRBN

# Site 0 [RESPONSIVE] q=0.300 verdict=NEAR
# Site 6 [CRYPTIC] q=0.436 verdict=MISS
# Site 511 [RESPONSIVE] q=0.414 verdict=MISS
# Site 8 [INERT] q=0.404 verdict=MISS
# Site 3008 [RESPONSIVE] q=0.399 verdict=MISS
# Site 4002 [INERT] q=0.390 verdict=MISS
# Site 4511 [RESPONSIVE] q=0.386 verdict=MISS
# Site 5517 [DYNAMIC] q=0.384 verdict=MISS
# Site 1518 [DYNAMIC] q=0.379 verdict=MISS
# Site 5518 [DYNAMIC] q=0.379 verdict=MISS
# Site 5519 [DYNAMIC] q=0.379 verdict=MISS
# Site 3007 [RESPONSIVE] q=0.371 verdict=MISS
# Site 7 [RESPONSIVE] q=0.358 verdict=MISS
# Site 3010 [RESPONSIVE] q=0.353 verdict=MISS
# Site 1517 [DYNAMIC] q=0.353 verdict=MISS
# Site 1 [INERT] q=0.352 verdict=MISS
# Site 4001 [INERT] q=0.329 verdict=MISS
# Site 3 [INERT] q=0.135 verdict=MISS
# Site 4 [RESPONSIVE] q=0.557 verdict=EXCELLENT
# Site 3522 [RESPONSIVE] q=0.485 verdict=EXCELLENT
zoom query_CRBN

# Verdict colour legend:
#   STRONG          -> red
#   GOOD_BOTH       -> orange
#   GOOD_DIST       -> yellow
#   GOOD_JACCARD    -> green
#   NEAR            -> cyan
#   WEAK            -> blue
#   MISS            -> grey60
