# PRISM-4D pub baseline validation overlay — CDK2_allosteric
# Generated by prism_pub_baseline_validator.py

load /mnt/storage/prism-outputs/blind_validation/B02_CDK2_allosteric/prep/1HCL_clean.pdb, query_CDK2_allosteric
hide everything, query_CDK2_allosteric
show cartoon,    query_CDK2_allosteric
color grey80,    query_CDK2_allosteric

# Site 3 [RESPONSIVE] q=0.387 verdict=STRONG
# Site 10 [INERT] q=0.413 verdict=NEAR
# Site 8 [RESPONSIVE] q=0.391 verdict=NEAR
# Site 5 [INERT] q=0.373 verdict=NEAR
# Site 4511 [DYNAMIC] q=0.369 verdict=NEAR
# Site 1 [RESPONSIVE] q=0.384 verdict=MISS
# Site 511 [CRYPTIC] q=0.366 verdict=MISS
# Site 7 [RESPONSIVE] q=0.356 verdict=MISS
# Site 4005 [INERT] q=0.316 verdict=MISS
# Site 4 [DYNAMIC] q=0.264 verdict=MISS
# Site 4004 [DYNAMIC] q=0.248 verdict=MISS
# Site 4006 [RESPONSIVE] q=0.450 verdict=EXCELLENT
# Site 4002 [RESPONSIVE] q=0.448 verdict=EXCELLENT
# Site 4000 [INERT] q=0.445 verdict=EXCELLENT
# Site 4510 [INERT] q=0.439 verdict=EXCELLENT
# Site 3517 [INERT] q=0.439 verdict=EXCELLENT
# Site 510 [INERT] q=0.418 verdict=EXCELLENT
# Site 2 [DYNAMIC] q=0.416 verdict=EXCELLENT
# Site 3518 [DYNAMIC] q=0.407 verdict=EXCELLENT
# Site 512 [INERT] q=0.401 verdict=EXCELLENT
zoom query_CDK2_allosteric

# Verdict colour legend:
#   STRONG          -> red
#   GOOD_BOTH       -> orange
#   GOOD_DIST       -> yellow
#   GOOD_JACCARD    -> green
#   NEAR            -> cyan
#   WEAK            -> blue
#   MISS            -> grey60
