"""Async dispatch of PRISM-4D active-learning GPU campaigns."""

from __future__ import annotations

import asyncio
import os
import stat
from dataclasses import dataclass
from pathlib import Path

from prism_dstw.orchestration.topology_compiler import TopologyCompileResult


REPO_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_LAUNCH_DIR = REPO_ROOT / "bin"
DEFAULT_OUTPUT_ROOT = REPO_ROOT / "campaigns/glp1r_aleniglipron/track_a_active_learning"
DEFAULT_RUNTIME_ENV = Path(
    "/media/diddy/PRISM-LBS/prism-glp1r-aleniglipron-workspace/"
    "20260518T031002Z/02_RUNTIME_CONFIG/glp1r_runtime.env"
)
DEFAULT_RUN_ONE = Path(
    "/media/diddy/PRISM-LBS/prism-glp1r-aleniglipron-workspace/"
    "20260518T031002Z/bin/run-one-glp1r-replica.sh"
)


@dataclass(frozen=True)
class CampaignTask:
    generated_id: str
    condition_id: str
    pid: int
    launch_script: Path
    expected_output_dir: Path
    process: asyncio.subprocess.Process


class AsyncCampaignDispatcher:
    """Generate and launch PRISM-4D n80 active-learning campaigns."""

    def __init__(
        self,
        *,
        launch_dir: Path = DEFAULT_LAUNCH_DIR,
        output_root: Path = DEFAULT_OUTPUT_ROOT,
        runtime_env: Path = DEFAULT_RUNTIME_ENV,
        run_one: Path = DEFAULT_RUN_ONE,
        max_parallel: int = 1,
    ) -> None:
        if max_parallel < 1:
            raise ValueError("max_parallel must be positive")
        self.launch_dir = launch_dir
        self.output_root = output_root
        self.runtime_env = runtime_env
        self.run_one = run_one
        self.max_parallel = max_parallel

    def launch_script_path(self, generated_id: str) -> Path:
        safe_generated_id = "".join(char if char.isalnum() or char in {"_", "-"} else "_" for char in generated_id)
        return self.launch_dir / f"launch-n80-active-learning-{safe_generated_id}.sh"

    def expected_output_dir(self, generated_id: str) -> Path:
        safe_generated_id = "".join(char if char.isalnum() or char in {"_", "-"} else "_" for char in generated_id)
        return self.output_root / safe_generated_id / "05_RESULTS"

    def write_launch_script(self, compiled: TopologyCompileResult) -> Path:
        output_dir = self.expected_output_dir(compiled.generated_id)
        script = self.launch_script_path(compiled.generated_id)
        text = f"""#!/usr/bin/env bash
set -euo pipefail

# Generated by prism_dstw.orchestration.campaign_dispatcher.AsyncCampaignDispatcher.
# Required active-learning physics flags:
#   --multi-differential --hysteresis --prism-therm

REPO_ROOT="${{PRISM_REPO_ROOT:-{REPO_ROOT.as_posix()}}}"
RUNTIME_ENV="${{PRISM_RUNTIME_ENV:-{self.runtime_env.as_posix()}}}"
RUN_ONE="${{PRISM_RUN_ONE:-{self.run_one.as_posix()}}}"
CONDITION_ID="${{1:-{compiled.condition_id}}}"
TOPOLOGY_JSON="${{2:-{compiled.topology_path.as_posix()}}}"
OUTPUT_ROOT="${{3:-{output_dir.as_posix()}}}"
START_REPLICA="${{4:-0}}"
END_REPLICA="${{5:-79}}"
MAX_PARALLEL="${{PRISM_ACTIVE_LEARNING_MAX_PARALLEL:-{self.max_parallel}}}"
REQUIRED_FLAGS=(--multi-differential --hysteresis --prism-therm)

if [[ -f "$RUNTIME_ENV" ]]; then
  source "$RUNTIME_ENV"
fi

export PRISM_CAMPAIGN_ID="${{PRISM_CAMPAIGN_ID:-track_a_active_learning_{compiled.generated_id}}}"
export PRISM_REPLICAS="${{PRISM_REPLICAS:-80}}"
export PRISM_STREAMS_PER_REPLICA="${{PRISM_STREAMS_PER_REPLICA:-20}}"
export PRISM_GLP1R_OUTPUT_ROOT="$OUTPUT_ROOT"
export PRISM_ENGINE_FLAGS="${{PRISM_ENGINE_FLAGS:-}} ${{REQUIRED_FLAGS[*]}}"

if [[ ! -f "$TOPOLOGY_JSON" ]]; then
  echo "missing topology: $TOPOLOGY_JSON" >&2
  exit 2
fi

if [[ ! -x "$RUN_ONE" ]]; then
  echo "missing executable run-one launcher: $RUN_ONE" >&2
  exit 2
fi

mkdir -p "$OUTPUT_ROOT"
echo "condition_id=$CONDITION_ID"
echo "topology_json=$TOPOLOGY_JSON"
echo "output_root=$OUTPUT_ROOT"
echo "engine_flags=$PRISM_ENGINE_FLAGS"

active=0
for replica_id in $(seq "$START_REPLICA" "$END_REPLICA"); do
  (
    "$RUN_ONE" "$CONDITION_ID" "$TOPOLOGY_JSON" "$replica_id"
  ) &
  active=$((active + 1))
  if (( active >= MAX_PARALLEL )); then
    wait -n
    active=$((active - 1))
  fi
done

wait
"""
        script.parent.mkdir(parents=True, exist_ok=True)
        script.write_text(text, encoding="utf-8")
        mode = script.stat().st_mode
        script.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
        return script

    async def dispatch(self, compiled: TopologyCompileResult) -> CampaignTask:
        script = self.write_launch_script(compiled)
        output_dir = self.expected_output_dir(compiled.generated_id)
        env = os.environ.copy()
        env.setdefault("PRISM_ACTIVE_LEARNING_MAX_PARALLEL", str(self.max_parallel))
        process = await asyncio.create_subprocess_exec(
            "bash",
            str(script),
            cwd=REPO_ROOT,
            env=env,
        )
        if process.pid is None:
            raise RuntimeError("PRISM-4D campaign subprocess did not expose a PID")
        return CampaignTask(
            generated_id=compiled.generated_id,
            condition_id=compiled.condition_id,
            pid=process.pid,
            launch_script=script,
            expected_output_dir=output_dir,
            process=process,
        )


__all__ = ["AsyncCampaignDispatcher", "CampaignTask"]
