# PRISM4D Binding Site Visualization
# Generated by prism-nhs
# Industry-standard pocket visualization

# Setup
bg_color white
set cartoon_fancy_helices, 1
set cartoon_side_chain_helper, 1
set surface_quality, 1

# Load your structure (adjust path as needed)
# load 1nkp_dimer.topology.pdb, protein
# show cartoon, protein
# color gray80, protein

# ========== Site 1 (ActiveSite) [DRUGGABLE] ==========
select pocket_1_lining, (chain A and resi 64) or (chain A and resi 63) or (chain A and resi 67) or (chain B and resi 150) or (chain A and resi 65) or (chain A and resi 66) or (chain B and resi 146) or (chain A and resi 60) or (chain A and resi 68) or (chain A and resi 62) or (chain A and resi 61) or (chain B and resi 142) or (chain A and resi 59) or (chain B and resi 143) or (chain A and resi 69) or (chain B and resi 147) or (chain A and resi 71) or (chain B and resi 149) or (chain A and resi 70) or (chain B and resi 153) or (chain B and resi 145)
show sticks, pocket_1_lining
set stick_radius, 0.15, pocket_1_lining
select pocket_1_hydrophobic, (chain A and resi 64) or (chain A and resi 63) or (chain A and resi 67) or (chain A and resi 65) or (chain A and resi 66) or (chain A and resi 60) or (chain A and resi 68) or (chain A and resi 62) or (chain A and resi 61) or (chain A and resi 59) or (chain A and resi 69) or (chain A and resi 71) or (chain A and resi 70)
color tv_yellow, pocket_1_hydrophobic
create pocket_1_surface, pocket_1_lining
show surface, pocket_1_surface
set surface_color, slate, pocket_1_surface
set transparency, 0.7, pocket_1_surface
pseudoatom pocket_1_center, pos=[59.073, 49.083, 49.577]
show spheres, pocket_1_center
set sphere_scale, 0.5, pocket_1_center
color red, pocket_1_center
group pocket_1, pocket_1_lining pocket_1_surface pocket_1_center pocket_1_hydrophobic

# ========== Site 2 (ActiveSite) [DRUGGABLE] ==========
select pocket_2_lining, (chain A and resi 81) or (chain A and resi 77) or (chain A and resi 78) or (chain B and resi 160) or (chain A and resi 74) or (chain A and resi 79) or (chain B and resi 164) or (chain A and resi 76) or (chain A and resi 80) or (chain A and resi 75) or (chain B and resi 163) or (chain A and resi 82) or (chain A and resi 73) or (chain B and resi 161) or (chain B and resi 157) or (chain B and resi 156) or (chain B and resi 159) or (chain A and resi 84) or (chain B and resi 167)
show sticks, pocket_2_lining
set stick_radius, 0.15, pocket_2_lining
select pocket_2_catalytic, (chain A and resi 81) or (chain A and resi 77) or (chain A and resi 78) or (chain B and resi 160) or (chain A and resi 74) or (chain A and resi 79) or (chain B and resi 164) or (chain A and resi 76) or (chain A and resi 80) or (chain A and resi 75) or (chain B and resi 163) or (chain A and resi 82) or (chain A and resi 73) or (chain B and resi 161) or (chain B and resi 157) or (chain B and resi 159) or (chain A and resi 84) or (chain B and resi 167)
color magenta, pocket_2_catalytic
create pocket_2_surface, pocket_2_lining
show surface, pocket_2_surface
set surface_color, slate, pocket_2_surface
set transparency, 0.7, pocket_2_surface
pseudoatom pocket_2_center, pos=[55.188, 34.439, 62.736]
show spheres, pocket_2_center
set sphere_scale, 0.5, pocket_2_center
color red, pocket_2_center
group pocket_2, pocket_2_lining pocket_2_surface pocket_2_center pocket_2_catalytic

# ========== Site 3 (ActiveSite) [DRUGGABLE] ==========
select pocket_3_lining, (chain A and resi 8) or (chain A and resi 11) or (chain A and resi 7) or (chain A and resi 9) or (chain A and resi 12) or (chain A and resi 10) or (chain A and resi 6) or (chain A and resi 5) or (chain A and resi 4) or (chain A and resi 13) or (chain A and resi 3) or (chain A and resi 14)
show sticks, pocket_3_lining
set stick_radius, 0.15, pocket_3_lining
select pocket_3_catalytic, (chain A and resi 11) or (chain A and resi 9) or (chain A and resi 12) or (chain A and resi 10) or (chain A and resi 13) or (chain A and resi 14)
color magenta, pocket_3_catalytic
create pocket_3_surface, pocket_3_lining
show surface, pocket_3_surface
set surface_color, slate, pocket_3_surface
set transparency, 0.7, pocket_3_surface
pseudoatom pocket_3_center, pos=[70.494, 96.644, 35.759]
show spheres, pocket_3_center
set sphere_scale, 0.5, pocket_3_center
color red, pocket_3_center
group pocket_3, pocket_3_lining pocket_3_surface pocket_3_center pocket_3_catalytic

group all_pockets, pocket_1 pocket_2 pocket_3

# ========== Color Legend ==========
# Magenta = Catalytic residues (GLU, ASP, HIS, SER, CYS, LYS)
# Green = Aromatic residues (PHE, TYR, TRP) - pi-stacking
# Yellow = Hydrophobic residues (ALA, VAL, LEU, ILE, MET, PRO)
# Slate surface = Pocket cavity
# Red sphere = Druggable site centroid
# Gray sphere = Non-druggable site centroid

# ========== Usage Tips ==========
# To view specific pocket: disable all_pockets, enable pocket_N
# To zoom on pocket: zoom pocket_N_lining
# To show H-bonds: select donors, pocket_N_lining; distance hbonds, donors, acceptors, 3.5
# To label residues: label pocket_N_lining and name CA, "%s%s" % (resn, resi)
