# PRISM-4D pub baseline validation overlay — cGAS
# Generated by prism_pub_baseline_validator.py

load /mnt/storage/prism-outputs/blind_validation/B06_cGAS/prep/4KM5_clean.pdb, query_cGAS
hide everything, query_cGAS
show cartoon,    query_cGAS
color grey80,    query_cGAS

# Site 3002 [DYNAMIC] q=0.440 verdict=STRONG
# Site 3014 [RESPONSIVE] q=0.435 verdict=STRONG
# Site 4015 [INERT] q=0.429 verdict=STRONG
# Site 3517 [INERT] q=0.423 verdict=STRONG
# Site 3006 [DYNAMIC] q=0.409 verdict=STRONG
# Site 516 [RESPONSIVE] q=0.394 verdict=STRONG
# Site 522 [INERT] q=0.290 verdict=STRONG
# Site 3016 [DYNAMIC] q=0.426 verdict=NEAR
# Site 3533 [RESPONSIVE] q=0.424 verdict=NEAR
# Site 4526 [RESPONSIVE] q=0.420 verdict=NEAR
# Site 4012 [RESPONSIVE] q=0.385 verdict=NEAR
# Site 1527 [RESPONSIVE] q=0.333 verdict=NEAR
# Site 4525 [RESPONSIVE] q=0.307 verdict=NEAR
# Site 4527 [RESPONSIVE] q=0.275 verdict=NEAR
# Site 4002 [DYNAMIC] q=0.454 verdict=MISS
# Site 3536 [DYNAMIC] q=0.449 verdict=MISS
# Site 4006 [DYNAMIC] q=0.374 verdict=MISS
# Site 1525 [RESPONSIVE] q=0.366 verdict=MISS
# Site 521 [INERT] q=0.344 verdict=MISS
# Site 1526 [RESPONSIVE] q=0.263 verdict=MISS
zoom query_cGAS

# Verdict colour legend:
#   STRONG          -> red
#   GOOD_BOTH       -> orange
#   GOOD_DIST       -> yellow
#   GOOD_JACCARD    -> green
#   NEAR            -> cyan
#   WEAK            -> blue
#   MISS            -> grey60
