# PRISM-4D pub baseline validation overlay — HRAS_Q61H
# Generated by prism_pub_baseline_validator.py

load /mnt/storage/prism-outputs/blind_validation/B01_HRAS_Q61H/prep/4L9S_clean.pdb, query_HRAS_Q61H
hide everything, query_HRAS_Q61H
show cartoon,    query_HRAS_Q61H
color grey80,    query_HRAS_Q61H

# Site 1 [INERT] q=0.442 verdict=STRONG
# Site 4002 [RESPONSIVE] q=0.420 verdict=STRONG
# Site 4001 [INERT] q=0.409 verdict=STRONG
# Site 4006 [RESPONSIVE] q=0.354 verdict=NEAR
# Site 0 [INERT] q=0.414 verdict=MISS
# Site 4 [DYNAMIC] q=0.504 verdict=EXCELLENT
# Site 5 [DYNAMIC] q=0.446 verdict=EXCELLENT
# Site 3 [RESPONSIVE] q=0.441 verdict=EXCELLENT
# Site 7 [DYNAMIC] q=0.411 verdict=EXCELLENT
# Site 2007 [RESPONSIVE] q=0.396 verdict=EXCELLENT
zoom query_HRAS_Q61H

# Verdict colour legend:
#   STRONG          -> red
#   GOOD_BOTH       -> orange
#   GOOD_DIST       -> yellow
#   GOOD_JACCARD    -> green
#   NEAR            -> cyan
#   WEAK            -> blue
#   MISS            -> grey60
