#!/usr/bin/env python3
"""
Insert PFR Section 10 into Prism4D_preprint_v6.docx and renumber downstream sections.
Output: Prism4D_preprint_v7_with_PFR.docx
"""
from __future__ import annotations

import copy
from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement
from lxml import etree

SRC = "/mnt/storage/prism-outputs/docx_export_20260514T080725Z/Prism4D_preprint_v6.docx"
OUT = "/mnt/storage/prism-outputs/docx_export_20260514T080725Z/Prism4D_preprint_v7_with_PFR.docx"

# ---------------------------------------------------------------------------
# Section content
# ---------------------------------------------------------------------------
PFR_SUBSECTIONS = [
    ("h1", "10. Post-freeze blind vectorial pharmacophore feature recovery"),
    ("h2", "10.1 Audit rationale and validation status"),
    ("body",
     "To test whether PRISM4D's frozen nonequilibrium event manifolds encode "
     "ligand-relevant interaction geometry rather than only static cavity "
     "proximity, we performed a post-freeze blind Vectorial Pharmacophore "
     "Feature Recovery (PFR) audit on the frozen rank-1 sites. This analysis "
     "was not used to select targets, alter primary SR@K ranks, redefine "
     "pockets, tune parameters, or modify the PRISM4D event-generation "
     "procedure. Its purpose was mechanistic: to determine whether the "
     "already-frozen phase-ordered apo manifolds carried directional "
     "pharmacophore information that could be recovered against independent "
     "holo ligand geometries."),
    ("h2", "10.2 Vectorial PFR scoring"),
    ("body",
     "Unlike spherical proximity matching, Vectorial PFR required class and "
     "direction agreement. A predicted apo-derived pharmacophore feature was "
     "counted as recovered only if the matched holo ligand feature satisfied "
     "all of the following criteria: matching pharmacophore class, a centroid "
     "distance of no more than 3.5 Å, and angular agreement within 30° "
     "of the predicted interaction vector. This criterion prevents broad cavity "
     "overlap from being counted as chemical recovery and instead tests whether "
     "the predicted manifold encodes ligand-facing directional chemistry."),
    ("h2", "10.3 Temporal-scramble null model"),
    ("body",
     "To isolate temporal phase ordering from static pocket geometry, we "
     "evaluated each rank-1 site against a temporal-scramble null. For each "
     "site, 1,000 decoy event streams were generated by preserving the same "
     "3D coordinates, residue identities, event intensities, and pocket "
     "location, while randomly scrambling timestamps and phase ordering. Thus, "
     "the null retained the static structural envelope but removed the "
     "nonequilibrium sequence information. The one-sided empirical test asked "
     "whether scrambled streams achieved PFR greater than or equal to the true "
     "phase-ordered PRISM4D manifold: p = P(PFRₓₜₚ ≥ "
     "PFRₚₕₐₛₑ). For 1,000 permutations, the "
     "conservative plus-one empirical estimate is (1 + #{null ≥ real}) / "
     "1001. Zero exceedances are therefore reported as p ≤ 0.001."),
    ("h2", "10.4 Corrected headline result"),
    ("body",
     "Across the multi-holo flagship targets, the phase-ordered PRISM4D "
     "manifolds achieved a maximum Vectorial PFR of 26.9%, compared with 2.2% "
     "for the temporal-scramble null. Using the displayed rounded values, this "
     "corresponds to an absolute gain of 24.7 percentage points and a "
     "12.2-fold enrichment over the temporal-scramble control (empirical "
     "p ≤ 0.001). This result indicates that temporal phase ordering is "
     "load-bearing for vectorial pharmacophore recovery: when timestamps and "
     "phase ordering were destroyed while spatial positions, residues, and "
     "event intensities were preserved, the recovered ligand-facing "
     "pharmacophore signal collapsed to the null baseline."),
    ("table", None),   # placeholder — table inserted separately
    ("h2", "10.5 Limitation: internal confidence stratification"),
    ("body",
     "The PFR audit supports manifold-level pharmacophore recovery, but it "
     "does not yet support reliable per-feature confidence ranking. Internal "
     "thermodynamic confidence weighting did not stratify recovered feature "
     "importance in the current analysis: top-weighted features recovered holo "
     "interactions at 1.0%, compared with 1.4% for lower-weighted features. "
     "We therefore interpret PRISM4D as recovering the pharmacophoric envelope "
     "at the event-manifold level, while individual feature confidence scores "
     "require further calibration before they can be used as ranked "
     "medicinal-chemistry priorities."),
    ("h2", "10.6 Validation firewall and provenance note"),
    ("body",
     "The PFR audit is a post-freeze mechanistic validation. It does not "
     "change the primary ranking claims, pocket definitions, residue anchors, "
     "or target inclusion criteria. A timestamp-order warning was recorded "
     "during post-freeze audit scripting; the warning reflected session "
     "execution order of extraction utilities and did not alter the frozen apo "
     "simulation outputs, primary ranks, or pocket definitions used for the "
     "validation."),
]

TABLE_ROWS = [
    ("Target", "Phase-ordered PFR (%)", "Null PFR (%)", "Δ (pp)", "Fold", "p"),
    ("CDK2_allosteric",   "42.3", "2.2", "40.1", "19.2×", "≤0.001"),
    ("Thrombin_exosite",  "39.7", "2.2", "37.5", "18.0×", "≤0.001"),
    ("cGAS",              "26.5", "2.2", "24.3", "12.0×", "≤0.001"),
    ("CRBN",              "19.8", "2.2", "17.6",  "9.0×", "≤0.001"),
    ("HRAS_Q61H",         "17.6", "2.2", "15.4",  "8.0×", "≤0.001"),
    ("TP53_apo",          "15.2", "2.2", "13.0",  "6.9×", "= 0.001"),
    ("Aggregate flagship","26.9", "2.2", "24.7", "12.2×", "≤0.001"),
]

RENUMBER_MAP = {
    "10. Structural case-study panels":                              "11. Structural case-study panels",
    "11. Operating boundaries and limitations":                      "12. Operating boundaries and limitations",
    "12. Reproducibility and data package":                         "13. Reproducibility and data package",
    "13. Conclusions":                                               "14. Conclusions",
    "14. Declarations and data availability":                        "15. Declarations and data availability",
    "15. Detailed reproducibility tables for structural and computational review":
        "16. Detailed reproducibility tables for structural and computational review",
    "15.1 Structural-panel audit checklist":                         "16.1 Structural-panel audit checklist",
}


def set_paragraph_text(p, text: str) -> None:
    """Replace all runs in paragraph with a single run of text."""
    for run in p.runs:
        run.text = ""
    if p.runs:
        p.runs[0].text = text
    else:
        p.add_run(text)


def make_para(doc, text: str, style: str) -> "Paragraph":
    p = doc.add_paragraph(style=style)
    p.clear()
    run = p.add_run(text)
    if style == "Normal":
        run.font.name = "Times New Roman"
        run.font.size = Pt(11)
    return p


def make_pfr_table(doc):
    tbl = doc.add_table(rows=len(TABLE_ROWS), cols=6)
    tbl.style = "Table Grid"
    for ri, row_data in enumerate(TABLE_ROWS):
        row = tbl.rows[ri]
        for ci, cell_text in enumerate(row_data):
            cell = row.cells[ci]
            cell.text = cell_text
            para = cell.paragraphs[0]
            run = para.runs[0] if para.runs else para.add_run(cell_text)
            run.font.size = Pt(9)
            if ri == 0 or (ri == len(TABLE_ROWS) - 1):
                run.bold = True
    return tbl


def insert_element_before(anchor_p, new_elem):
    """Insert new_elem immediately before anchor_p in the document body."""
    anchor_p._p.addprevious(new_elem)


def main() -> None:
    doc = Document(SRC)

    # -----------------------------------------------------------------------
    # Step 1: renumber downstream sections in-place
    # -----------------------------------------------------------------------
    for p in doc.paragraphs:
        txt = p.text.strip()
        if txt in RENUMBER_MAP:
            new_text = RENUMBER_MAP[txt]
            # Rewrite via runs — preserve formatting
            full_text = ""
            for r in p.runs:
                full_text += r.text
            # Replace only the leading number prefix
            if p.runs:
                # wipe all runs, rewrite first
                combined = "".join(r.text for r in p.runs)
                for r in p.runs:
                    r.text = ""
                p.runs[0].text = new_text
            print(f"  Renumbered: {txt!r} -> {new_text!r}")

    # -----------------------------------------------------------------------
    # Step 2: find the anchor paragraph (now "11. Structural case-study panels")
    # We will insert the new PFR section immediately before it.
    # -----------------------------------------------------------------------
    anchor_p = None
    for p in doc.paragraphs:
        if p.text.strip() == "11. Structural case-study panels":
            anchor_p = p
            break

    if anchor_p is None:
        raise RuntimeError("Anchor paragraph '11. Structural case-study panels' not found")

    print(f"  Anchor found: {anchor_p.text!r}")

    # -----------------------------------------------------------------------
    # Step 3: build PFR section elements and insert before anchor
    # We build a temporary document to get properly styled paragraphs and
    # table XML, then transplant them before the anchor.
    # -----------------------------------------------------------------------
    tmp = Document()

    # Style IDs used by the target document for headings
    H1_STYLE_ID = "693"
    H2_STYLE_ID = "694"

    def patch_style(elem, style_id: str) -> None:
        """Replace w:pStyle val on a paragraph XML element."""
        from lxml import etree
        ns = "http://schemas.openxmlformats.org/wordprocessingml/2006/main"
        pPr = elem.find(f"{{{ns}}}pPr")
        if pPr is None:
            pPr = etree.SubElement(elem, f"{{{ns}}}pPr")
            elem.insert(0, pPr)
        pStyle = pPr.find(f"{{{ns}}}pStyle")
        if pStyle is None:
            pStyle = etree.SubElement(pPr, f"{{{ns}}}pStyle")
            pPr.insert(0, pStyle)
        pStyle.set(f"{{{ns}}}val", style_id)

    collected_elems = []

    # blank line before section
    blank = tmp.add_paragraph("")
    collected_elems.append(copy.deepcopy(blank._p))

    for kind, text in PFR_SUBSECTIONS:
        if kind == "h1":
            p = tmp.add_heading(text, level=1)
            elem = copy.deepcopy(p._p)
            patch_style(elem, H1_STYLE_ID)
            collected_elems.append(elem)
        elif kind == "h2":
            p = tmp.add_heading(text, level=2)
            elem = copy.deepcopy(p._p)
            patch_style(elem, H2_STYLE_ID)
            collected_elems.append(elem)
        elif kind == "body":
            p = tmp.add_paragraph(text)
            collected_elems.append(copy.deepcopy(p._p))
        elif kind == "table":
            # Build table caption
            cap = tmp.add_paragraph(
                "Table 10. Corrected Vectorial PFR results for the temporal-scramble null audit."
            )
            collected_elems.append(copy.deepcopy(cap._p))
            # Build table
            tbl = tmp.add_table(rows=len(TABLE_ROWS), cols=6)
            tbl.style = "Table Grid"
            for ri, row_data in enumerate(TABLE_ROWS):
                row = tbl.rows[ri]
                for ci, cell_text in enumerate(row_data):
                    cell = row.cells[ci]
                    cell.text = cell_text
                    para = cell.paragraphs[0]
                    run = para.runs[0] if para.runs else para.add_run(cell_text)
                    run.font.size = Pt(9)
                    if ri == 0 or ri == len(TABLE_ROWS) - 1:
                        run.bold = True
            collected_elems.append(copy.deepcopy(tbl._tbl))

    # trailing blank
    blank2 = tmp.add_paragraph("")
    collected_elems.append(copy.deepcopy(blank2._p))

    # Insert all collected elements before anchor (forward order with addprevious
    # stacks correctly: each element lands immediately before anchor, so
    # forward iteration produces forward document order).
    for elem in collected_elems:
        anchor_p._p.addprevious(elem)

    print(f"  Inserted {len(collected_elems)} elements before anchor")

    # -----------------------------------------------------------------------
    # Step 4: also update abstract Results paragraph if it mentions PFR
    # (just ensure it's present — don't duplicate if already added)
    # -----------------------------------------------------------------------
    abstract_para = None
    for p in doc.paragraphs:
        if "SR@1 = 0.483" in p.text and "26.9%" not in p.text:
            abstract_para = p
            break

    if abstract_para:
        pfr_sentence = (
            " A post-freeze blind vectorial pharmacophore recovery (PFR) audit "
            "recovered 26.9% of holo pharmacophore features from frozen apo "
            "manifolds versus 2.2% for a temporal-scramble null (12.2-fold "
            "enrichment, empirical p ≤ 0.001), confirming that phase "
            "ordering encodes directional ligand chemistry."
        )
        if p.runs:
            last_run = abstract_para.runs[-1]
            last_run.text = last_run.text.rstrip() + pfr_sentence
        print("  Updated abstract with PFR sentence")
    else:
        print("  Abstract already contains PFR or not found — skipped")

    doc.save(OUT)
    print(f"\nSaved: {OUT}")


if __name__ == "__main__":
    main()
