# PRISM-4D pub baseline validation overlay — MDM2
# Generated by prism_pub_baseline_validator.py

load /mnt/storage/prism-outputs/blind_validation/B04_MDM2/prep/1YCR_clean.pdb, query_MDM2
hide everything, query_MDM2
show cartoon,    query_MDM2
color grey80,    query_MDM2

# Site 1 [RESPONSIVE] q=0.411 verdict=STRONG
# Site 4505 [DYNAMIC] q=0.399 verdict=STRONG
# Site 4 [INERT] q=0.398 verdict=STRONG
# Site 4001 [INERT] q=0.394 verdict=STRONG
# Site 4003 [DYNAMIC] q=0.392 verdict=STRONG
# Site 3002 [RESPONSIVE] q=0.386 verdict=MISS
# Site 4002 [RESPONSIVE] q=0.341 verdict=MISS
# Site 6505 [DYNAMIC] q=0.441 verdict=EXCELLENT
# Site 505 [DYNAMIC] q=0.418 verdict=EXCELLENT
# Site 2505 [DYNAMIC] q=0.399 verdict=EXCELLENT
zoom query_MDM2

# Verdict colour legend:
#   STRONG          -> red
#   GOOD_BOTH       -> orange
#   GOOD_DIST       -> yellow
#   GOOD_JACCARD    -> green
#   NEAR            -> cyan
#   WEAK            -> blue
#   MISS            -> grey60
