# PRISM4D Binding Site Visualization
# Generated by prism-nhs
# Industry-standard pocket visualization

# Setup
bg_color white
set cartoon_fancy_helices, 1
set cartoon_side_chain_helper, 1
set surface_quality, 1

# Load your structure (adjust path as needed)
# load 07_FructoseAldolase_apo.topology.pdb, protein
# show cartoon, protein
# color gray80, protein

# ========== Site 1 (ActiveSite) ==========
select pocket_1_lining, (chain C and resi 985) or (chain C and resi 1020) or (chain C and resi 989) or (chain C and resi 986) or (chain C and resi 992) or (chain C and resi 981) or (chain C and resi 938) or (chain C and resi 953) or (chain C and resi 987) or (chain B and resi 624) or (chain C and resi 984) or (chain C and resi 1019) or (chain C and resi 991) or (chain C and resi 982) or (chain C and resi 1022) or (chain C and resi 988) or (chain C and resi 934) or (chain B and resi 623) or (chain C and resi 948) or (chain C and resi 990) or (chain C and resi 955) or (chain C and resi 980) or (chain C and resi 952) or (chain B and resi 619) or (chain C and resi 983) or (chain C and resi 1021) or (chain C and resi 1018)
show sticks, pocket_1_lining
set stick_radius, 0.15, pocket_1_lining
select pocket_1_catalytic, (chain C and resi 1020) or (chain C and resi 1019) or (chain C and resi 1022) or (chain C and resi 1021) or (chain C and resi 1018)
color magenta, pocket_1_catalytic
select pocket_1_hydrophobic, (chain C and resi 985) or (chain C and resi 989) or (chain C and resi 986) or (chain C and resi 992) or (chain C and resi 981) or (chain C and resi 938) or (chain C and resi 953) or (chain C and resi 987) or (chain C and resi 984) or (chain C and resi 991) or (chain C and resi 982) or (chain C and resi 988) or (chain C and resi 948) or (chain C and resi 990) or (chain C and resi 955) or (chain C and resi 980) or (chain C and resi 952) or (chain C and resi 983)
color tv_yellow, pocket_1_hydrophobic
create pocket_1_surface, pocket_1_lining
show surface, pocket_1_surface
set surface_color, slate, pocket_1_surface
set transparency, 0.7, pocket_1_surface
pseudoatom pocket_1_center, pos=[62.328, 10.410, -1.692]
show spheres, pocket_1_center
set sphere_scale, 0.5, pocket_1_center
color gray50, pocket_1_center
group pocket_1, pocket_1_lining pocket_1_surface pocket_1_center pocket_1_catalytic pocket_1_hydrophobic

# ========== Site 2 (ActiveSite) ==========
select pocket_2_lining, (chain A and resi 162) or (chain A and resi 210) or (chain A and resi 163) or (chain A and resi 166) or (chain A and resi 159) or (chain D and resi 1302) or (chain A and resi 164) or (chain A and resi 167) or (chain A and resi 207) or (chain A and resi 211) or (chain A and resi 161) or (chain A and resi 214) or (chain A and resi 206) or (chain A and resi 165) or (chain A and resi 160) or (chain A and resi 213) or (chain A and resi 158) or (chain A and resi 209) or (chain A and resi 150) or (chain A and resi 157) or (chain D and resi 1306) or (chain A and resi 169) or (chain A and resi 208)
show sticks, pocket_2_lining
set stick_radius, 0.15, pocket_2_lining
select pocket_2_catalytic, (chain A and resi 210) or (chain A and resi 166) or (chain A and resi 164) or (chain A and resi 167) or (chain A and resi 207) or (chain A and resi 211) or (chain A and resi 214) or (chain A and resi 206) or (chain A and resi 165) or (chain A and resi 213) or (chain A and resi 209) or (chain A and resi 169) or (chain A and resi 208)
color magenta, pocket_2_catalytic
select pocket_2_aromatic, (chain D and resi 1302) or (chain D and resi 1306)
color forest, pocket_2_aromatic
create pocket_2_surface, pocket_2_lining
show surface, pocket_2_surface
set surface_color, slate, pocket_2_surface
set transparency, 0.7, pocket_2_surface
pseudoatom pocket_2_center, pos=[37.024, 16.324, 8.505]
show spheres, pocket_2_center
set sphere_scale, 0.5, pocket_2_center
color gray50, pocket_2_center
group pocket_2, pocket_2_lining pocket_2_surface pocket_2_center pocket_2_catalytic pocket_2_aromatic

group all_pockets, pocket_1 pocket_2

# ========== Color Legend ==========
# Magenta = Catalytic residues (GLU, ASP, HIS, SER, CYS, LYS)
# Green = Aromatic residues (PHE, TYR, TRP) - pi-stacking
# Yellow = Hydrophobic residues (ALA, VAL, LEU, ILE, MET, PRO)
# Slate surface = Pocket cavity
# Red sphere = Druggable site centroid
# Gray sphere = Non-druggable site centroid

# ========== Usage Tips ==========
# To view specific pocket: disable all_pockets, enable pocket_N
# To zoom on pocket: zoom pocket_N_lining
# To show H-bonds: select donors, pocket_N_lining; distance hbonds, donors, acceptors, 3.5
# To label residues: label pocket_N_lining and name CA, "%s%s" % (resn, resi)
