# PRISM-4D pub baseline validation overlay — TEAD1
# Generated by prism_pub_baseline_validator.py

load /mnt/storage/prism-outputs/blind_validation/B07_TEAD1/prep/3KYS_clean.pdb, query_TEAD1
hide everything, query_TEAD1
show cartoon,    query_TEAD1
color grey80,    query_TEAD1

# Site 4510 [RESPONSIVE] q=0.458 verdict=STRONG
# Site 510 [DYNAMIC] q=0.451 verdict=STRONG
# Site 3520 [DYNAMIC] q=0.436 verdict=STRONG
# Site 511 [INERT] q=0.403 verdict=STRONG
# Site 1519 [RESPONSIVE] q=0.374 verdict=STRONG
# Site 8 [RESPONSIVE] q=0.373 verdict=STRONG
# Site 1512 [RESPONSIVE] q=0.371 verdict=STRONG
# Site 1514 [RESPONSIVE] q=0.371 verdict=STRONG
# Site 4008 [DYNAMIC] q=0.370 verdict=STRONG
# Site 1518 [RESPONSIVE] q=0.363 verdict=STRONG
# Site 1520 [RESPONSIVE] q=0.360 verdict=STRONG
# Site 4003 [RESPONSIVE] q=0.279 verdict=STRONG
# Site 5 [DYNAMIC] q=0.408 verdict=NEAR
# Site 4005 [DYNAMIC] q=0.387 verdict=NEAR
# Site 3522 [DYNAMIC] q=0.381 verdict=NEAR
# Site 1513 [INERT] q=0.360 verdict=NEAR
# Site 1515 [RESPONSIVE] q=0.303 verdict=NEAR
# Site 1516 [INERT] q=0.298 verdict=NEAR
# Site 1517 [RESPONSIVE] q=0.273 verdict=NEAR
# Site 0 [INERT] q=0.433 verdict=MISS
zoom query_TEAD1

# Verdict colour legend:
#   STRONG          -> red
#   GOOD_BOTH       -> orange
#   GOOD_DIST       -> yellow
#   GOOD_JACCARD    -> green
#   NEAR            -> cyan
#   WEAK            -> blue
#   MISS            -> grey60
