# PRISM4D Binding Site Visualization
# Generated by prism-nhs
# Industry-standard pocket visualization

# Setup
bg_color white
set cartoon_fancy_helices, 1
set cartoon_side_chain_helper, 1
set surface_quality, 1

# Load your structure (adjust path as needed)
# load 07_FructoseAldolase_apo.topology.pdb, protein
# show cartoon, protein
# color gray80, protein

# ========== Site 1 (ActiveSite) ==========
select pocket_1_lining, (chain A and resi 269) or (chain A and resi 228) or (chain A and resi 300) or (chain A and resi 299) or (chain A and resi 270) or (chain A and resi 268) or (chain A and resi 301) or (chain A and resi 30) or (chain A and resi 271) or (chain A and resi 186) or (chain A and resi 267) or (chain A and resi 298) or (chain A and resi 76) or (chain A and resi 145) or (chain A and resi 229) or (chain A and resi 303) or (chain A and resi 188) or (chain A and resi 28) or (chain A and resi 304) or (chain A and resi 302) or (chain A and resi 230) or (chain A and resi 231) or (chain A and resi 32) or (chain A and resi 29) or (chain A and resi 278) or (chain A and resi 147) or (chain A and resi 297) or (chain A and resi 273) or (chain A and resi 184) or (chain A and resi 33)
show sticks, pocket_1_lining
set stick_radius, 0.15, pocket_1_lining
select pocket_1_catalytic, (chain A and resi 186) or (chain A and resi 145) or (chain A and resi 188) or (chain A and resi 184) or (chain A and resi 33)
color magenta, pocket_1_catalytic
select pocket_1_hydrophobic, (chain A and resi 269) or (chain A and resi 228) or (chain A and resi 270) or (chain A and resi 268) or (chain A and resi 271) or (chain A and resi 267) or (chain A and resi 76) or (chain A and resi 229) or (chain A and resi 230) or (chain A and resi 231) or (chain A and resi 278) or (chain A and resi 273)
color tv_yellow, pocket_1_hydrophobic
create pocket_1_surface, pocket_1_lining
show surface, pocket_1_surface
set surface_color, slate, pocket_1_surface
set transparency, 0.7, pocket_1_surface
pseudoatom pocket_1_center, pos=[22.132, 25.425, 22.148]
show spheres, pocket_1_center
set sphere_scale, 0.5, pocket_1_center
color gray50, pocket_1_center
group pocket_1, pocket_1_lining pocket_1_surface pocket_1_center pocket_1_catalytic pocket_1_hydrophobic

# ========== Site 2 (ActiveSite) ==========
select pocket_2_lining, (chain B and resi 630) or (chain B and resi 631) or (chain B and resi 662) or (chain B and resi 661) or (chain B and resi 660) or (chain B and resi 591) or (chain B and resi 632) or (chain B and resi 629) or (chain B and resi 391) or (chain B and resi 592) or (chain B and resi 663) or (chain B and resi 590) or (chain B and resi 547) or (chain B and resi 645) or (chain B and resi 594) or (chain B and resi 633) or (chain B and resi 390) or (chain B and resi 439) or (chain B and resi 385) or (chain B and resi 589) or (chain B and resi 393) or (chain B and resi 659) or (chain B and resi 549) or (chain B and resi 384) or (chain B and resi 628)
show sticks, pocket_2_lining
set stick_radius, 0.15, pocket_2_lining
select pocket_2_catalytic, (chain B and resi 591) or (chain B and resi 592) or (chain B and resi 590) or (chain B and resi 547) or (chain B and resi 594) or (chain B and resi 589) or (chain B and resi 549)
color magenta, pocket_2_catalytic
select pocket_2_hydrophobic, (chain B and resi 391) or (chain B and resi 645) or (chain B and resi 633) or (chain B and resi 390) or (chain B and resi 439) or (chain B and resi 385) or (chain B and resi 393) or (chain B and resi 384)
color tv_yellow, pocket_2_hydrophobic
create pocket_2_surface, pocket_2_lining
show surface, pocket_2_surface
set surface_color, slate, pocket_2_surface
set transparency, 0.7, pocket_2_surface
pseudoatom pocket_2_center, pos=[62.539, -0.632, 19.012]
show spheres, pocket_2_center
set sphere_scale, 0.5, pocket_2_center
color gray50, pocket_2_center
group pocket_2, pocket_2_lining pocket_2_surface pocket_2_center pocket_2_catalytic pocket_2_hydrophobic

group all_pockets, pocket_1 pocket_2

# ========== Color Legend ==========
# Magenta = Catalytic residues (GLU, ASP, HIS, SER, CYS, LYS)
# Green = Aromatic residues (PHE, TYR, TRP) - pi-stacking
# Yellow = Hydrophobic residues (ALA, VAL, LEU, ILE, MET, PRO)
# Slate surface = Pocket cavity
# Red sphere = Druggable site centroid
# Gray sphere = Non-druggable site centroid

# ========== Usage Tips ==========
# To view specific pocket: disable all_pockets, enable pocket_N
# To zoom on pocket: zoom pocket_N_lining
# To show H-bonds: select donors, pocket_N_lining; distance hbonds, donors, acceptors, 3.5
# To label residues: label pocket_N_lining and name CA, "%s%s" % (resn, resi)
