#!/usr/bin/env python3
"""Generate the 80-replica holo-state campaign launcher without running the engine."""

from __future__ import annotations

import argparse
import hashlib
import os
import stat
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_WORKSPACE = Path("/media/diddy/PRISM-LBS/prism-glp1r-aleniglipron-workspace/20260518T031002Z")
DEFAULT_RUNTIME_ENV = DEFAULT_WORKSPACE / "02_RUNTIME_CONFIG/glp1r_runtime.env"
DEFAULT_RUN_ONE = DEFAULT_WORKSPACE / "bin/run-one-glp1r-replica.sh"
DEFAULT_TOPOLOGY = REPO_ROOT / "04_TOPOLOGIES/glp1r_6XOX_HOLO_ALENI.topology.json"
DEFAULT_OUTPUT = REPO_ROOT / "bin/launch-n80-holo-aleniglipron.sh"
DEFAULT_RAW_OUTPUT = REPO_ROOT / "campaigns/glp1r_aleniglipron/holo_state_n80_raw"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--workspace", type=Path, default=DEFAULT_WORKSPACE)
    parser.add_argument("--runtime-env", type=Path, default=DEFAULT_RUNTIME_ENV)
    parser.add_argument("--run-one", type=Path, default=DEFAULT_RUN_ONE)
    parser.add_argument("--topology", type=Path, default=DEFAULT_TOPOLOGY)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--raw-output", type=Path, default=DEFAULT_RAW_OUTPUT)
    return parser.parse_args()


def emit(message: str) -> None:
    sys.stdout.write(message + "\n")


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def shell_quote(path: Path) -> str:
    return "'" + path.as_posix().replace("'", "'\"'\"'") + "'"


def launcher_text(
    *,
    workspace: Path,
    runtime_env: Path,
    run_one: Path,
    topology: Path,
    raw_output: Path,
) -> str:
    runtime_hash = sha256_file(runtime_env)
    run_one_hash = sha256_file(run_one)
    topology_hash = sha256_file(topology)
    return f"""#!/usr/bin/env bash
set -euo pipefail

# Generated by scripts/generate_holo_campaign_launch.py.
# Runtime env SHA-256: {runtime_hash}
# run-one launcher SHA-256: {run_one_hash}
# Holo topology SHA-256: {topology_hash}
# Protocol parity: sourced PRISM_ENGINE_FLAGS carries the original 4-group
# ThermalShock/Equilibrium/UVAromatic/Hysteresis multi-differential protocol.

REPO_ROOT="${{PRISM_REPO_ROOT:-{REPO_ROOT.as_posix()}}}"
WS="${{PRISM_GLP1R_WORKSPACE:-{workspace.as_posix()}}}"
RUNTIME_ENV="${{PRISM_RUNTIME_ENV:-{runtime_env.as_posix()}}}"
RUN_ONE="${{PRISM_RUN_ONE:-{run_one.as_posix()}}}"

source "$RUNTIME_ENV"

export PRISM_CAMPAIGN_ID="${{PRISM_CAMPAIGN_ID:-glp1r_aleniglipron_holo_n80}}"
export PRISM_BASE_SEED="${{PRISM_BASE_SEED:-42}}"
export PRISM_REPLICAS="${{PRISM_REPLICAS:-80}}"
export PRISM_STREAMS_PER_REPLICA="${{PRISM_STREAMS_PER_REPLICA:-20}}"
export PRISM_GLP1R_OUTPUT_ROOT="${{PRISM_GLP1R_OUTPUT_ROOT:-{raw_output.as_posix()}}}"
export PRISM_GLP1R_RAW_ARCHIVE_AFTER_REPLICA="${{PRISM_GLP1R_RAW_ARCHIVE_AFTER_REPLICA:-0}}"
export PRISM_GLP1R_COMPACT_ARCHIVE_AFTER_MATERIALIZE="${{PRISM_GLP1R_COMPACT_ARCHIVE_AFTER_MATERIALIZE:-0}}"

CONDITION_ID="${{1:-glp1r_6XOX_HOLO_ALENI}}"
TOPOLOGY_JSON="${{2:-{topology.as_posix()}}}"
START_REPLICA="${{3:-0}}"
END_REPLICA="${{4:-79}}"
MAX_PARALLEL="${{PRISM_HOLO_MAX_PARALLEL:-1}}"

if [[ ! -f "$TOPOLOGY_JSON" ]]; then
  echo "missing holo topology: $TOPOLOGY_JSON" >&2
  exit 2
fi

if [[ ! -x "$RUN_ONE" ]]; then
  echo "missing executable run-one launcher: $RUN_ONE" >&2
  exit 2
fi

mkdir -p "$PRISM_GLP1R_OUTPUT_ROOT"

echo "condition_id=$CONDITION_ID"
echo "topology_json=$TOPOLOGY_JSON"
echo "replica_range=$START_REPLICA..$END_REPLICA"
echo "output_root=$PRISM_GLP1R_OUTPUT_ROOT"
echo "protocol_groups=ThermalShock,Equilibrium,UVAromatic,Hysteresis"
echo "engine_flags=$PRISM_ENGINE_FLAGS"

active=0
for replica_id in $(seq "$START_REPLICA" "$END_REPLICA"); do
  (
    export PRISM_CAMPAIGN_ID
    export PRISM_BASE_SEED
    export PRISM_REPLICAS
    export PRISM_STREAMS_PER_REPLICA
    export PRISM_GLP1R_OUTPUT_ROOT
    export PRISM_GLP1R_RAW_ARCHIVE_AFTER_REPLICA
    export PRISM_GLP1R_COMPACT_ARCHIVE_AFTER_MATERIALIZE
    "$RUN_ONE" "$CONDITION_ID" "$TOPOLOGY_JSON" "$replica_id"
  ) &
  active=$((active + 1))
  if (( active >= MAX_PARALLEL )); then
    wait -n
    active=$((active - 1))
  fi
done

wait
"""


def main() -> int:
    args = parse_args()
    workspace = Path(args.workspace)
    runtime_env = Path(args.runtime_env)
    run_one = Path(args.run_one)
    topology = Path(args.topology)
    output = Path(args.output)
    raw_output = Path(args.raw_output)
    for path in (workspace, runtime_env, run_one, topology):
        if not path.exists():
            raise FileNotFoundError(path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        launcher_text(
            workspace=workspace,
            runtime_env=runtime_env,
            run_one=run_one,
            topology=topology,
            raw_output=raw_output,
        )
    )
    mode = output.stat().st_mode
    output.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    emit(f"wrote {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
