#!/usr/bin/env bash
set -euo pipefail

ENV_ROOT="${PRISM_DOCK_ENV:-/mnt/storage/prism_env_copies/prism_dock_portable_20260529}"
SCRATCH_ROOT="${PRISM_SCRATCH_ROOT:-/mnt/storage/prism-scratch/Prism4D-bio}"

export PRISM_DOCK_ENV="$ENV_ROOT"
export PRISM_DOCK_PYTHON="${PRISM_DOCK_PYTHON:-$ENV_ROOT/bin/python}"
export PRISM_AMBERHOME="${PRISM_AMBERHOME:-$ENV_ROOT}"
export PRISM_ANTECHAMBER="${PRISM_ANTECHAMBER:-$ENV_ROOT/bin/antechamber}"
export PRISM_OBABEL="${PRISM_OBABEL:-$ENV_ROOT/bin/obabel}"
export PRISM_UNIDOCK="${PRISM_UNIDOCK:-$ENV_ROOT/bin/unidock}"
export PRISM_GNINA="${PRISM_GNINA:-$ENV_ROOT/bin/gnina}"
export BABEL_LIBDIR="${BABEL_LIBDIR:-$ENV_ROOT/lib/openbabel/3.1.0}"
export BABEL_DATADIR="${BABEL_DATADIR:-$ENV_ROOT/share/openbabel/3.1.0}"
export PRISM_SCRATCH_ROOT="$SCRATCH_ROOT"
export PRISM_CANONICAL_RUNTIME_STRICT="${PRISM_CANONICAL_RUNTIME_STRICT:-1}"
export PATH="$ENV_ROOT/bin:$PATH"

mkdir -p "$PRISM_SCRATCH_ROOT"

echo "PRISM_DOCK_ENV=$PRISM_DOCK_ENV"
echo "PRISM_DOCK_PYTHON=$PRISM_DOCK_PYTHON"
echo "PRISM_SCRATCH_ROOT=$PRISM_SCRATCH_ROOT"
echo "PRISM_CANONICAL_RUNTIME_STRICT=$PRISM_CANONICAL_RUNTIME_STRICT"
echo "PRISM_ANTECHAMBER=$PRISM_ANTECHAMBER"
echo "PRISM_OBABEL=$PRISM_OBABEL"
echo "PRISM_UNIDOCK=$PRISM_UNIDOCK"
echo "PRISM_GNINA=$PRISM_GNINA"
echo "BABEL_LIBDIR=$BABEL_LIBDIR"
echo "BABEL_DATADIR=$BABEL_DATADIR"
