# PRISM-4D pub baseline validation overlay — TP53_apo
# Generated by prism_pub_baseline_validator.py

load /mnt/storage/prism-outputs/blind_validation/B05_TP53_R175H/prep/2OCJ_clean.pdb, query_TP53_apo
hide everything, query_TP53_apo
show cartoon,    query_TP53_apo
color grey80,    query_TP53_apo

# Site 510 [RESPONSIVE] q=0.500 verdict=STRONG
# Site 4510 [INERT] q=0.453 verdict=STRONG
# Site 3006 [INERT] q=0.406 verdict=STRONG
# Site 1513 [INERT] q=0.405 verdict=STRONG
# Site 1516 [INERT] q=0.392 verdict=STRONG
# Site 1514 [INERT] q=0.366 verdict=STRONG
# Site 4005 [RESPONSIVE] q=0.358 verdict=STRONG
# Site 1517 [INERT] q=0.357 verdict=STRONG
# Site 1515 [INERT] q=0.353 verdict=STRONG
# Site 3520 [INERT] q=0.443 verdict=NEAR
# Site 8 [DYNAMIC] q=0.402 verdict=NEAR
# Site 3 [DYNAMIC] q=0.399 verdict=NEAR
# Site 7 [RESPONSIVE] q=0.390 verdict=NEAR
# Site 3008 [RESPONSIVE] q=0.368 verdict=NEAR
# Site 1512 [INERT] q=0.366 verdict=NEAR
# Site 511 [DYNAMIC] q=0.425 verdict=MISS
# Site 3000 [DYNAMIC] q=0.373 verdict=MISS
# Site 3523 [DYNAMIC] q=0.331 verdict=MISS
# Site 3002 [CRYPTIC] q=0.450 verdict=EXCELLENT
# Site 4509 [INERT] q=0.403 verdict=EXCELLENT
zoom query_TP53_apo

# Verdict colour legend:
#   STRONG          -> red
#   GOOD_BOTH       -> orange
#   GOOD_DIST       -> yellow
#   GOOD_JACCARD    -> green
#   NEAR            -> cyan
#   WEAK            -> blue
#   MISS            -> grey60
