# PRISM-4D pub baseline validation overlay — Thrombin_exosite
# Generated by prism_pub_baseline_validator.py

load /mnt/storage/prism-outputs/blind_validation/B09_Thrombin_exosite/prep/1PPB_clean.pdb, query_Thrombin_exosite
hide everything, query_Thrombin_exosite
show cartoon,    query_Thrombin_exosite
color grey80,    query_Thrombin_exosite

# Site 4509 [RESPONSIVE] q=0.468 verdict=STRONG
# Site 509 [RESPONSIVE] q=0.464 verdict=STRONG
# Site 0 [RESPONSIVE] q=0.452 verdict=STRONG
# Site 3526 [RESPONSIVE] q=0.429 verdict=STRONG
# Site 4517 [RESPONSIVE] q=0.391 verdict=STRONG
# Site 511 [RESPONSIVE] q=0.389 verdict=STRONG
# Site 4511 [CRYPTIC] q=0.375 verdict=STRONG
# Site 1516 [RESPONSIVE] q=0.361 verdict=STRONG
# Site 3002 [INERT] q=0.343 verdict=STRONG
# Site 1519 [RESPONSIVE] q=0.257 verdict=STRONG
# Site 4004 [INERT] q=0.472 verdict=MISS
# Site 4 [INERT] q=0.427 verdict=MISS
# Site 510 [DYNAMIC] q=0.426 verdict=MISS
# Site 4510 [DYNAMIC] q=0.394 verdict=MISS
# Site 1523 [RESPONSIVE] q=0.389 verdict=MISS
# Site 4003 [CRYPTIC] q=0.387 verdict=MISS
# Site 4522 [INERT] q=0.381 verdict=MISS
# Site 3524 [CRYPTIC] q=0.380 verdict=MISS
# Site 1522 [INERT] q=0.366 verdict=MISS
# Site 4512 [INERT] q=0.363 verdict=MISS
zoom query_Thrombin_exosite

# Verdict colour legend:
#   STRONG          -> red
#   GOOD_BOTH       -> orange
#   GOOD_DIST       -> yellow
#   GOOD_JACCARD    -> green
#   NEAR            -> cyan
#   WEAK            -> blue
#   MISS            -> grey60
